'use client';

import { ChangeEvent, FormEvent, useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { Bell, CalendarDays, Camera, ExternalLink, Languages, LogIn, LogOut, Mail, MapPin, MessageCircle, Navigation, Pencil, RefreshCw, Reply, Send, ShieldCheck, Smartphone, Trash2, UserRound, Users, X } from 'lucide-react';
import type { Session } from '@supabase/supabase-js';
import { fallbackMatches, fallbackPlayers, fallbackStandings, Match, PlayerStat, SEASON, SOURCE_URL, Standing, TEAM } from '@/lib/data';
import { supabase } from '@/lib/supabase';

type Lang='cs'|'en';
type Tab='matches'|'table'|'stats'|'history'|'h2h'|'admin';
type Attendance='yes'|'no'|'maybe'|null;
type Profile={id:string;display_name:string;role:string;user_id:string|null;avatar_url:string|null};
type AttendanceRow={status:'yes'|'no'|'maybe';player_id:string;players:{display_name:string;avatar_url:string|null}|null};
type Venue={code:string;name:string;address:string;notes:string|null};
type Season={season:string;label:string;year:number;phase:string;division:string|null;team_name:string;final_rank:number|null;played:number|null;wins:number|null;draws:number|null;losses:number|null;score:string|null;points:number|null};
type HistMatch={psmf_key:string;season:string;kickoff:string;venue_code:string|null;home_team:string;away_team:string;home_score:number;away_score:number;round:number;team_name:string};
type SeasonStat={season:string;player_name:string;games:number;goals:number};
type HistStanding={season:string;rank:number;team:string;played:number;wins:number;draws:number;losses:number;score:string;points:number};
type CommentRow={id:string;match_id:string;player_id:string;parent_id:string|null;body:string;created_at:string;updated_at:string;players:{display_name:string;avatar_url:string|null;role:string}|null};
type AdminPlayer={id:string;display_name:string;email:string|null;role:'player'|'captain'|'admin';active:boolean;user_id:string|null;avatar_url:string|null};

const copy={
 cs:{tagline:'JEDEN TÝM. JEDNA KABINA.',league:'PSMF · 5D · podzim 2026',verified:'Automatická synchronizace PSMF',refresh:'Obnovit PSMF',matches:'Zápasy',table:'Tabulka',stats:'Statistiky',history:'Historie',h2h:'Vzájemné zápasy',heading:'Jdeme hrát.',sub:'Potvrď účast a měj přehled o dalších zápasech.',next:'NEJBLIŽŠÍ ZÁPAS',away:'Venku',home:'Doma',count:'Počítáme s tebou?',yes:'Přijdu',no:'Nepřijdu',maybe:'Zatím nevím',cancel:'Zrušit odpověď',saved:'Uloženo do týmové kabiny.',upcoming:'Další zápasy',past:'Odehráno',pos:'Poř.',team:'Tým',played:'Z',wins:'V',draws:'R',losses:'P',score:'Skóre',pts:'B',player:'Hráč',goals:'Góly',games:'Zápasy',account:'Týmová kabina',login:'Přihlásit',logout:'Odhlásit',signup:'Vytvořit účet',email:'E-mail',password:'Heslo',choosePlayer:'Který hráč jsi?',haveAccount:'Už mám účet',newAccount:'Jsem tu poprvé',signedAs:'Přihlášen jako',loginNeeded:'Pro týmové funkce se přihlas.',responses:'Odpovědi týmu',noResponses:'Zatím nikdo neodpověděl.',confirmEmail:'Účet je vytvořený. Potvrď e-mail a potom se přihlas.',playerLinked:'Účet je propojen s hráčem.',genericError:'Něco se nepovedlo. Zkus to prosím znovu.',synced:'PSMF aktualizováno včetně historie.',address:'Adresa',google:'Google Maps',waze:'Waze',resend:'Poslat ověřovací e-mail znovu',resent:'Ověřovací e-mail byl znovu odeslán.',testReminder:'Poslat test reminder sobě',testReminderSent:'Testovací reminder byl odeslán jen na tvůj e-mail.',comments:'Komentáře',writeComment:'Napiš zprávu k zápasu…',send:'Odeslat',reply:'Odpovědět',edit:'Upravit',delete:'Smazat',noComments:'Zatím žádné komentáře.',photo:'Profilová fotka',uploadPhoto:'Nahrát fotku',career:'Kariéra od 2020',season:'Sezóna',rank:'Umístění',record:'Bilance',selectOpponent:'Vyber soupeře',meetings:'Zápasy',h2hRecord:'Bilance V–R–P',manageTeam:'Správa týmu',role:'Role',active:'Aktivní',unlink:'Odpojit účet',captain:'Kapitán',admin:'Admin',regularPlayer:'Hráč',noAccount:'Bez účtu',adminSaved:'Změna uložena.',adminTab:'Správa',noH2H:'Zatím žádný odehraný vzájemný zápas.',pushEnable:'Zapnout upozornění',pushEnabled:'Upozornění zapnutá',pushDenied:'Upozornění jsou v prohlížeči zakázaná.',pushTest:'Poslat test push sobě',pushTestSent:'Testovací push byl odeslán.',iosInstall:'Na iPhonu nejdřív otevři Sdílet → Přidat na plochu, spusť Kabinu z ikony a potom zapni upozornění.',adminPush:'Týmová push notifikace',pushTitle:'Nadpis',pushMessage:'Zpráva',pushRecipients:'Příjemci',pushAll:'Všichni hráči s účtem',pushSend:'Odeslat push',pushSent:'Push notifikace byla odeslána.'},
 en:{tagline:'ONE TEAM. ONE LOCKER ROOM.',league:'PSMF · 5D · autumn 2026',verified:'Automatic PSMF sync',refresh:'Refresh PSMF',matches:'Matches',table:'Table',stats:'Stats',history:'History',h2h:'Head-to-head',heading:"We're playing.",sub:'Confirm your availability and keep track of upcoming matches.',next:'NEXT MATCH',away:'Away',home:'Home',count:'Can we count on you?',yes:"I'm in",no:"I'm out",maybe:'Not sure yet',cancel:'Clear answer',saved:'Saved to the team locker room.',upcoming:'Upcoming matches',past:'Results',pos:'Pos.',team:'Team',played:'P',wins:'W',draws:'D',losses:'L',score:'Score',pts:'Pts',player:'Player',goals:'Goals',games:'Games',account:'Team locker room',login:'Sign in',logout:'Sign out',signup:'Create account',email:'Email',password:'Password',choosePlayer:'Which player are you?',haveAccount:'I already have an account',newAccount:"I'm new here",signedAs:'Signed in as',loginNeeded:'Sign in for team features.',responses:'Team responses',noResponses:'No responses yet.',confirmEmail:'Account created. Confirm your email and then sign in.',playerLinked:'Your account is linked to the player.',genericError:'Something went wrong. Please try again.',synced:'PSMF refreshed including history.',address:'Address',google:'Google Maps',waze:'Waze',resend:'Resend confirmation email',resent:'Confirmation email sent again.',testReminder:'Send test reminder to me',testReminderSent:'Test reminder was sent only to your email.',comments:'Comments',writeComment:'Write a match message…',send:'Send',reply:'Reply',edit:'Edit',delete:'Delete',noComments:'No comments yet.',photo:'Profile photo',uploadPhoto:'Upload photo',career:'Career since 2020',season:'Season',rank:'Rank',record:'Record',selectOpponent:'Choose opponent',meetings:'Matches',h2hRecord:'W–D–L',manageTeam:'Manage team',role:'Role',active:'Active',unlink:'Unlink account',captain:'Captain',admin:'Admin',regularPlayer:'Player',noAccount:'No account',adminSaved:'Change saved.',adminTab:'Admin',noH2H:'No completed head-to-head match yet.',pushEnable:'Enable notifications',pushEnabled:'Notifications enabled',pushDenied:'Notifications are blocked in the browser.',pushTest:'Send test push to me',pushTestSent:'Test push was sent.',iosInstall:'On iPhone, first use Share → Add to Home Screen, open the locker room from the icon, then enable notifications.',adminPush:'Team push notification',pushTitle:'Title',pushMessage:'Message',pushRecipients:'Recipients',pushAll:'All players with accounts',pushSend:'Send push',pushSent:'Push notification sent.'}
} as const;

function fmtDate(iso:string,lang:Lang){return new Intl.DateTimeFormat(lang==='cs'?'cs-CZ':'en-GB',{day:'numeric',month:'long'}).format(new Date(`${iso}T12:00:00`));}
function fmtDateTime(iso:string,lang:Lang){return new Intl.DateTimeFormat(lang==='cs'?'cs-CZ':'en-GB',{day:'numeric',month:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(iso));}
function googleMaps(address:string){return `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(address)}`;}
function waze(address:string){return `https://www.waze.com/ul?q=${encodeURIComponent(address)}&navigate=yes`;}
function ours(name:string){return name.startsWith('Pěstební dělníci');}
function outcome(home:string,away:string,hs:number|null|undefined,as:number|null|undefined){if(hs==null||as==null)return '';const gf=ours(home)?hs:as;const ga=ours(home)?as:hs;return gf>ga?'win':gf<ga?'loss':'draw';}
function avatar(name:string,url?:string|null,size='md'){return url?<img className={`avatar ${size}`} src={url} alt={name}/>:<span className={`avatar avatarFallback ${size}`}>{name.split(' ').map(x=>x[0]).slice(0,2).join('').toUpperCase()}</span>;}

export default function KabinaApp(){
 const [lang,setLang]=useState<Lang>('cs'); const [tab,setTab]=useState<Tab>('matches'); const t=copy[lang];
 const [session,setSession]=useState<Session|null>(null); const [profile,setProfile]=useState<Profile|null>(null);
 const [attendance,setAttendance]=useState<Attendance>(null); const [attendanceRows,setAttendanceRows]=useState<AttendanceRow[]>([]);
 const [authOpen,setAuthOpen]=useState(false); const [authMode,setAuthMode]=useState<'login'|'signup'>('login'); const [email,setEmail]=useState(''); const [password,setPassword]=useState('');
 const [matches,setMatches]=useState<Match[]>(fallbackMatches); const [players,setPlayers]=useState<PlayerStat[]>(fallbackPlayers); const [standings,setStandings]=useState<Standing[]>(fallbackStandings); const [venues,setVenues]=useState<Record<string,Venue>>({}); const [venueOpen,setVenueOpen]=useState<Venue|null>(null);
 const [selectedPlayer,setSelectedPlayer]=useState<string>(fallbackPlayers[0].name); const [authMessage,setAuthMessage]=useState(''); const [authBusy,setAuthBusy]=useState(false); const [saving,setSaving]=useState(false); const [syncing,setSyncing]=useState(false); const [reminderBusy,setReminderBusy]=useState(false);
 const [seasons,setSeasons]=useState<Season[]>([]); const [historyMatches,setHistoryMatches]=useState<HistMatch[]>([]); const [historyStandings,setHistoryStandings]=useState<HistStanding[]>([]); const [seasonStats,setSeasonStats]=useState<SeasonStat[]>([]); const [historySeason,setHistorySeason]=useState(''); const [h2hOpponent,setH2hOpponent]=useState('');
 const [comments,setComments]=useState<CommentRow[]>([]); const [commentDrafts,setCommentDrafts]=useState<Record<string,string>>({});
 const [adminOpen,setAdminOpen]=useState(false); const [adminPlayers,setAdminPlayers]=useState<AdminPlayer[]>([]); const [adminBusy,setAdminBusy]=useState<string|null>(null); const [replyTo,setReplyTo]=useState<Record<string,string|null>>({}); const [commentBusy,setCommentBusy]=useState<string|null>(null); const avatarInput=useRef<HTMLInputElement|null>(null); const [avatarBusy,setAvatarBusy]=useState(false);
 const [pushReady,setPushReady]=useState(false); const [pushPermission,setPushPermission]=useState<'default'|'granted'|'denied'>('default'); const [pushBusy,setPushBusy]=useState(false);
 const [isIos,setIsIos]=useState(false); const [isStandalone,setIsStandalone]=useState(false);
 const [adminPushTitle,setAdminPushTitle]=useState('⚽ Pěstební dělníci A'); const [adminPushMessage,setAdminPushMessage]=useState(''); const [adminPushPlayers,setAdminPushPlayers]=useState<string[]>([]); const [adminPushBusy,setAdminPushBusy]=useState(false);

 useEffect(()=>{
   if(typeof window==='undefined')return;
   const ua=window.navigator.userAgent;
   setIsIos(/iPad|iPhone|iPod/.test(ua) || (navigator.platform==='MacIntel' && navigator.maxTouchPoints>1));
   setIsStandalone(window.matchMedia('(display-mode: standalone)').matches || Boolean((navigator as any).standalone));
   if('Notification' in window)setPushPermission(Notification.permission as 'default'|'granted'|'denied');
   const appId=process.env.NEXT_PUBLIC_ONESIGNAL_APP_ID;
   if(!appId)return;
   const w=window as any;
   w.OneSignalDeferred=w.OneSignalDeferred||[];
   w.OneSignalDeferred.push(async(OneSignal:any)=>{
     try{
       await OneSignal.init({appId,serviceWorkerPath:'/OneSignalSDKWorker.js',serviceWorkerParam:{scope:'/'},notifyButton:{enable:false}});
       setPushReady(true);
       if('Notification' in window)setPushPermission(Notification.permission as 'default'|'granted'|'denied');
     }catch(e){console.error('OneSignal init failed',e);}
   });
   if(!document.querySelector('script[data-onesignal-sdk]')){
     const script=document.createElement('script');
     script.src='https://cdn.onesignal.com/sdks/web/v16/OneSignalSDK.page.js';
     script.defer=true;script.dataset.onesignalSdk='1';document.head.appendChild(script);
   }
 },[]);

 useEffect(()=>{
   if(typeof window==='undefined' || !pushReady)return;
   const w=window as any; w.OneSignalDeferred=w.OneSignalDeferred||[];
   w.OneSignalDeferred.push(async(OneSignal:any)=>{
     try{if(profile?.id)await OneSignal.login(profile.id);else await OneSignal.logout();}catch(e){console.error('OneSignal identity failed',e);}
   });
 },[profile?.id,pushReady]);

 const loadPublicData=useCallback(async()=>{
   const [m,s,p,v,sea,hm,hs,ps]=await Promise.all([
    supabase.from('matches').select('id,psmf_key,kickoff,venue_code,home_team,away_team,home_score,away_score,season').eq('season',SEASON).order('kickoff'),
    supabase.from('standings').select('rank,team,played,wins,draws,losses,score,points').eq('season',SEASON).order('rank'),
    supabase.rpc('list_public_players'),
    supabase.from('venues').select('code,name,address,notes').order('code'),
    supabase.from('seasons').select('season,label,year,phase,division,team_name,final_rank,played,wins,draws,losses,score,points').order('year',{ascending:false}),
    supabase.from('historical_matches').select('psmf_key,season,kickoff,venue_code,home_team,away_team,home_score,away_score,round,team_name').order('kickoff',{ascending:false}),
    supabase.from('historical_standings').select('season,rank,team,played,wins,draws,losses,score,points').order('rank'),
    supabase.from('player_season_stats').select('season,player_name,games,goals')
   ]);
   if(m.data?.length)setMatches(m.data.map((r:any)=>{const d=new Date(r.kickoff);return{id:r.id,psmfKey:r.psmf_key,date:d.toLocaleDateString('en-CA',{timeZone:'Europe/Prague'}),time:d.toLocaleTimeString('cs-CZ',{timeZone:'Europe/Prague',hour:'2-digit',minute:'2-digit'}),venue:r.venue_code||'',home:r.home_team,away:r.away_team,round:Number(String(r.psmf_key).match(/r(\d+)$/)?.[1]||0),result:r.home_score==null?undefined:`${r.home_score}:${r.away_score}`,homeScore:r.home_score,awayScore:r.away_score,status:r.home_score==null?'upcoming':'past',season:r.season} as Match;}));
   if(s.data?.length)setStandings(s.data.map((r:any)=>[r.team,r.played,r.wins,r.draws,r.losses,r.score,r.points] as Standing));
   if(p.data?.length){const list=p.data.map((r:any)=>({name:r.display_name,games:r.psmf_games??0,goals:r.psmf_goals??0,avatarUrl:r.avatar_url??null}));setPlayers(list);setSelectedPlayer(prev=>list.some((x:PlayerStat)=>x.name===prev)?prev:list[0].name);}
   if(v.data?.length)setVenues(Object.fromEntries(v.data.map((r:any)=>[r.code,r as Venue])));
   if(sea.data?.length){const sorted=(sea.data as Season[]).sort((a,b)=>b.year-a.year||(b.phase==='podzim'?1:0)-(a.phase==='podzim'?1:0));setSeasons(sorted);setHistorySeason(prev=>prev||sorted[0]?.season||'');}
   if(hm.data)setHistoryMatches(hm.data as HistMatch[]); if(hs.data)setHistoryStandings(hs.data as HistStanding[]); if(ps.data)setSeasonStats(ps.data as SeasonStat[]);
 },[]);

 useEffect(()=>{loadPublicData();},[loadPublicData]);
 const next=useMemo(()=>matches.find(m=>m.status==='upcoming'),[matches]); const opponent=next?(next.home===TEAM?next.away:next.home):''; const nextKey=next?.psmfKey??'';

 const loadComments=useCallback(async()=>{if(!session){setComments([]);return;}const ids=matches.filter(m=>m.status==='upcoming'&&m.id).map(m=>m.id!) ;if(!ids.length)return;const {data}=await supabase.from('match_comments').select('id,match_id,player_id,parent_id,body,created_at,updated_at,players(display_name,avatar_url,role)').in('match_id',ids).order('created_at');if(data)setComments(data.map((r:any)=>({...r,players:Array.isArray(r.players)?r.players[0]??null:r.players??null})) as CommentRow[]);},[session,matches]);
 useEffect(()=>{loadComments();},[loadComments]);

 const loadCabin=useCallback(async(active:Session|null)=>{if(!active||!nextKey){setProfile(null);setAttendance(null);setAttendanceRows([]);return;}let {data:me}=await supabase.from('players').select('id,display_name,role,user_id,avatar_url').eq('user_id',active.user.id).maybeSingle();const pending=localStorage.getItem('pending-player-name');if(!me&&pending){const {error}=await supabase.rpc('claim_player',{player_name:pending});if(!error){localStorage.removeItem('pending-player-name');const r=await supabase.from('players').select('id,display_name,role,user_id,avatar_url').eq('user_id',active.user.id).maybeSingle();me=r.data;setAuthMessage(t.playerLinked);}}if(me){const {data:boot}=await supabase.rpc('bootstrap_admin');if(boot===true){const r=await supabase.from('players').select('id,display_name,role,user_id,avatar_url').eq('user_id',active.user.id).maybeSingle();me=r.data;}}setProfile(me as Profile|null);const mr=await supabase.from('matches').select('id').eq('psmf_key',nextKey).maybeSingle();if(!mr.data?.id)return;const board=await supabase.from('attendance').select('status,player_id,players(display_name,avatar_url)').eq('match_id',mr.data.id);const normalized=(board.data??[]).map((r:any)=>({...r,players:Array.isArray(r.players)?r.players[0]??null:r.players??null})) as AttendanceRow[];setAttendanceRows(normalized);if(me)setAttendance((normalized.find(r=>r.player_id===me!.id)?.status as Attendance)||null);},[nextKey,t.playerLinked]);
 useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session);loadCabin(data.session);});const {data:sub}=supabase.auth.onAuthStateChange((_e,s)=>{setSession(s);setTimeout(()=>loadCabin(s),0);});return()=>sub.subscription.unsubscribe();},[loadCabin]);

 async function refreshPsmf(){setSyncing(true);try{const r=await fetch('/api/sync-psmf',{cache:'no-store'});const body=await r.json().catch(()=>({}));if(!r.ok)throw new Error(body?.error||'sync');await loadPublicData();alert(t.synced);}catch(e:any){alert(e?.message||t.genericError);}finally{setSyncing(false);}}
 async function submitAuth(e:FormEvent){e.preventDefault();setAuthBusy(true);setAuthMessage('');try{if(authMode==='signup'){localStorage.setItem('pending-player-name',selectedPlayer);const {error}=await supabase.auth.signUp({email,password,options:{emailRedirectTo:window.location.origin}});if(error)throw error;setAuthMessage(t.confirmEmail);}else{const {error}=await supabase.auth.signInWithPassword({email,password});if(error)throw error;setAuthOpen(false);}}catch(e:any){setAuthMessage(e?.message||t.genericError);}finally{setAuthBusy(false);}}
 async function logout(){await supabase.auth.signOut();setProfile(null);setAttendance(null);setAttendanceRows([]);}
 async function resendConfirmation(){if(!email){setAuthMessage(lang==='cs'?'Nejdřív vyplň e-mail.':'Enter your email first.');return;}setAuthBusy(true);try{const {error}=await supabase.auth.resend({type:'signup',email,options:{emailRedirectTo:window.location.origin}});if(error)throw error;setAuthMessage(t.resent);}catch(e:any){setAuthMessage(e?.message||t.genericError);}finally{setAuthBusy(false);}}
 async function setA(v:Exclude<Attendance,null>){if(!session||!profile||!next?.id){setAuthOpen(true);return;}setSaving(true);try{const {error}=await supabase.from('attendance').upsert({match_id:next.id,player_id:profile.id,status:v,updated_at:new Date().toISOString()},{onConflict:'match_id,player_id'});if(error)throw error;setAttendance(v);await loadCabin(session);}catch(e:any){alert(e?.message||t.genericError);}finally{setSaving(false);}}
 async function clearA(){if(!profile||!next?.id)return;setSaving(true);try{const {error}=await supabase.from('attendance').delete().eq('match_id',next.id).eq('player_id',profile.id);if(error)throw error;setAttendance(null);await loadCabin(session);}catch(e:any){alert(e?.message||t.genericError);}finally{setSaving(false);}}
 async function sendTestReminder(){if(!session)return;setReminderBusy(true);try{const r=await fetch('/api/send-reminders',{method:'POST',headers:{Authorization:`Bearer ${session.access_token}`}});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b?.error||'reminder');alert(t.testReminderSent);}catch(e:any){alert(e?.message||t.genericError);}finally{setReminderBusy(false);}}
 async function enablePush(){
   if(!session||!profile){setAuthOpen(true);return;}
   if(isIos&&!isStandalone){alert(t.iosInstall);return;}
   if(pushPermission==='denied'){alert(t.pushDenied);return;}
   setPushBusy(true);
   try{
     const w=window as any;w.OneSignalDeferred=w.OneSignalDeferred||[];
     await new Promise<void>((resolve,reject)=>w.OneSignalDeferred.push(async(OneSignal:any)=>{try{await OneSignal.login(profile.id);await OneSignal.Notifications.requestPermission();setPushPermission(Notification.permission as 'default'|'granted'|'denied');resolve();}catch(e){reject(e);}}));
   }catch(e:any){alert(e?.message||t.genericError);}finally{setPushBusy(false);}
 }
 async function sendTestPush(){if(!session||!profile)return;setPushBusy(true);try{const r=await fetch('/api/push-notifications',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({mode:'test'})});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b?.error||'push');alert(t.pushTestSent);}catch(e:any){alert(e?.message||t.genericError);}finally{setPushBusy(false);}}
 async function sendAdminPush(){if(!session||profile?.role!=='admin')return;if(!adminPushTitle.trim()||!adminPushMessage.trim())return;setAdminPushBusy(true);try{const r=await fetch('/api/push-notifications',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({mode:'admin',title:adminPushTitle.trim(),message:adminPushMessage.trim(),playerIds:adminPushPlayers})});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b?.error||'push');alert(t.pushSent);setAdminPushMessage('');}catch(e:any){alert(e?.message||t.genericError);}finally{setAdminPushBusy(false);}}
 function openVenue(code:string){const v=venues[code];if(v)setVenueOpen(v);else window.open(googleMaps(`${code} PSMF Praha`),'_blank','noopener,noreferrer');}

 async function postComment(matchId:string,parentId:string|null=null){if(!profile){setAuthOpen(true);return;}const key=parentId?`${matchId}:${parentId}`:matchId;const body=(commentDrafts[key]||'').trim();if(!body)return;setCommentBusy(key);try{const {error}=await supabase.from('match_comments').insert({match_id:matchId,player_id:profile.id,parent_id:parentId,body});if(error)throw error;setCommentDrafts(d=>({...d,[key]:''}));setReplyTo(r=>({...r,[matchId]:null}));await loadComments();}catch(e:any){alert(e?.message||t.genericError);}finally{setCommentBusy(null);}}
 async function deleteComment(c:CommentRow){if(!confirm(lang==='cs'?'Smazat komentář?':'Delete comment?'))return;const {error}=await supabase.from('match_comments').delete().eq('id',c.id);if(error)alert(error.message);else await loadComments();}
 async function editComment(c:CommentRow){const body=prompt(lang==='cs'?'Upravit komentář':'Edit comment',c.body)?.trim();if(!body||body===c.body)return;const {error}=await supabase.from('match_comments').update({body,updated_at:new Date().toISOString()}).eq('id',c.id);if(error)alert(error.message);else await loadComments();}
 async function uploadAvatar(e:ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file||!session||!profile)return;if(file.size>5*1024*1024){alert('Max. 5 MB');return;}setAvatarBusy(true);try{const ext=file.name.split('.').pop()?.toLowerCase()||'jpg';const path=`${session.user.id}/avatar-${Date.now()}.${ext}`;const {error}=await supabase.storage.from('player-avatars').upload(path,file,{upsert:true});if(error)throw error;const {data}=supabase.storage.from('player-avatars').getPublicUrl(path);const rpc=await supabase.rpc('set_my_avatar',{url:data.publicUrl});if(rpc.error)throw rpc.error;setProfile({...profile,avatar_url:data.publicUrl});await loadPublicData();}catch(err:any){alert(err?.message||t.genericError);}finally{setAvatarBusy(false);e.target.value='';}}
 async function loadAdminPlayers(){if(profile?.role!=='admin')return;const {data,error}=await supabase.rpc('admin_list_players');if(error){alert(error.message);return;}setAdminPlayers((data||[]) as AdminPlayer[]);}
 async function openAdmin(){setAdminOpen(true);await loadAdminPlayers();}
 async function setPlayerRole(id:string,role:'player'|'captain'|'admin'){setAdminBusy(id);try{const {error}=await supabase.rpc('admin_set_player_role',{target_player_id:id,new_role:role});if(error)throw error;await loadAdminPlayers();if(id===profile?.id)await loadCabin(session);}catch(e:any){alert(e?.message||t.genericError);}finally{setAdminBusy(null);}}
 async function setPlayerActive(id:string,active:boolean){setAdminBusy(id);try{const {error}=await supabase.rpc('admin_set_player_active',{target_player_id:id,new_active:active});if(error)throw error;await loadAdminPlayers();}catch(e:any){alert(e?.message||t.genericError);}finally{setAdminBusy(null);}}
 async function unlinkPlayer(id:string){if(!confirm(lang==='cs'?'Odpojit účet od tohoto hráče?':'Unlink this account from the player?'))return;setAdminBusy(id);try{const {error}=await supabase.rpc('admin_unlink_player',{target_player_id:id});if(error)throw error;await loadAdminPlayers();}catch(e:any){alert(e?.message||t.genericError);}finally{setAdminBusy(null);}}


 const responseGroups={yes:attendanceRows.filter(r=>r.status==='yes'),maybe:attendanceRows.filter(r=>r.status==='maybe'),no:attendanceRows.filter(r=>r.status==='no')};
 const selectedSeason=seasons.find(s=>s.season===historySeason); const selectedSeasonMatches=historyMatches.filter(m=>m.season===historySeason).sort((a,b)=>+new Date(a.kickoff)-+new Date(b.kickoff)); const selectedHistoricalStanding=historyStandings.filter(r=>r.season===historySeason).sort((a,b)=>a.rank-b.rank);
 const opponents=useMemo(()=>Array.from(new Set([...historyMatches.flatMap(m=>[m.home_team,m.away_team]),...matches.flatMap(m=>[m.home,m.away])].filter(n=>!ours(n)))).sort((a,b)=>a.localeCompare(b,'cs')),[historyMatches,matches]);
 useEffect(()=>{if(!h2hOpponent&&opponents.length)setH2hOpponent(opponent&&opponents.includes(opponent)?opponent:opponents[0]);},[opponents,h2hOpponent,opponent]);
 const h2h=historyMatches.filter(m=>m.home_team===h2hOpponent||m.away_team===h2hOpponent).sort((a,b)=>+new Date(b.kickoff)-+new Date(a.kickoff));
 const h2hTotals=h2h.reduce((a,m)=>{const o=outcome(m.home_team,m.away_team,m.home_score,m.away_score);if(o==='win')a.w++;else if(o==='draw')a.d++;else if(o==='loss')a.l++;return a;},{w:0,d:0,l:0});
 const career=useMemo(()=>{const map=new Map<string,{name:string,games:number,goals:number}>();for(const r of seasonStats){const x=map.get(r.player_name)||{name:r.player_name,games:0,goals:0};x.games+=r.games;x.goals+=r.goals;map.set(r.player_name,x);}return [...map.values()].sort((a,b)=>b.goals-a.goals||b.games-a.games||a.name.localeCompare(b.name,'cs'));},[seasonStats]);

 function renderDiscussion(match:Match){if(!match.id)return null;const rows=comments.filter(c=>c.match_id===match.id);const roots=rows.filter(c=>!c.parent_id);const draft=commentDrafts[match.id]||'';return <div className="discussion"><div className="discussionTitle"><MessageCircle size={18}/><strong>{t.comments}</strong><span>{rows.length}</span></div>{session&&profile?<><div className="commentComposer"><textarea value={draft} maxLength={1000} placeholder={t.writeComment} onChange={e=>setCommentDrafts(d=>({...d,[match.id!]:e.target.value}))}/><button onClick={()=>postComment(match.id!)} disabled={!draft.trim()||commentBusy===match.id}>{t.send}</button></div>{roots.length===0&&<p className="muted smallText">{t.noComments}</p>}{roots.map(c=>renderCommentItem(c,rows.filter(r=>r.parent_id===c.id),match.id!))}</>:<button className="textBtn" onClick={()=>setAuthOpen(true)}>{t.loginNeeded}</button>}</div>;}
 function renderCommentItem(c:CommentRow,replies:CommentRow[],matchId:string){const canManage=profile&&(profile.id===c.player_id||profile.role==='admin'||profile.role==='captain');const rk=`${matchId}:${c.id}`;return <div className="commentThread"><div className="comment"><div>{avatar(c.players?.display_name||'?',c.players?.avatar_url,'sm')}</div><div className="commentBody"><div className="commentMeta"><strong>{c.players?.display_name||'Hráč'}</strong><span>{fmtDateTime(c.created_at,lang)}</span></div><p>{c.body}</p><div className="commentActions"><button onClick={()=>setReplyTo(r=>({...r,[matchId]:r[matchId]===c.id?null:c.id}))}><Reply size={14}/>{t.reply}</button>{canManage&&<><button onClick={()=>editComment(c)}><Pencil size={14}/>{t.edit}</button><button onClick={()=>deleteComment(c)}><Trash2 size={14}/>{t.delete}</button></>}</div></div></div>{replies.map(r=><div className="comment replyComment" key={r.id}><div>{avatar(r.players?.display_name||'?',r.players?.avatar_url,'sm')}</div><div className="commentBody"><div className="commentMeta"><strong>{r.players?.display_name||'Hráč'}</strong><span>{fmtDateTime(r.created_at,lang)}</span></div><p>{r.body}</p>{profile&&(profile.id===r.player_id||profile.role==='admin'||profile.role==='captain')&&<div className="commentActions"><button onClick={()=>editComment(r)}><Pencil size={14}/>{t.edit}</button><button onClick={()=>deleteComment(r)}><Trash2 size={14}/>{t.delete}</button></div>}</div></div>)}{replyTo[matchId]===c.id&&<div className="replyComposer"><input value={commentDrafts[rk]||''} maxLength={1000} placeholder={`${t.reply}…`} onChange={e=>setCommentDrafts(d=>({...d,[rk]:e.target.value}))}/><button onClick={()=>postComment(matchId,c.id)}>{t.send}</button></div>}</div>;}

 return <main className="shell">
  <header className="teamHeroHeader"><div className="heroShade"/><div className="heroHeaderContent"><div><div className="tag light">{t.tagline}</div><h1>Pěstební dělníci<br className="mobileBreak"/> A<span>.</span></h1></div><div className="actions"><button className="glassBtn" onClick={()=>setLang(lang==='cs'?'en':'cs')}><Languages size={18}/>{lang==='cs'?'EN':'CZ'}</button>{session?<button className="glassBtn" onClick={logout}><LogOut size={18}/><span className="desktopOnly">{t.logout}</span></button>:<button className="glassBtn" onClick={()=>{setAuthMode('login');setAuthOpen(true)}}><LogIn size={18}/><span className="desktopOnly">{t.login}</span></button>}</div></div></header>
  {profile&&<div className="signedStrip">{avatar(profile.display_name,profile.avatar_url,'sm')}<span>{t.signedAs}: <strong>{profile.display_name}</strong></span></div>}
  <section className="sourceCard"><div><strong>{t.league}</strong><div className="muted">{t.verified}</div></div><div className="actions"><button className="ghost" onClick={refreshPsmf} disabled={syncing}><RefreshCw size={18}/>{syncing?'…':t.refresh}</button><a href={SOURCE_URL} target="_blank" rel="noreferrer" className="ghost"><ExternalLink size={16}/></a></div></section>
  <nav className="tabs">{(['matches','table','stats','history','h2h'] as Tab[]).map(k=><button key={k} className={tab===k?'active':''} onClick={()=>setTab(k)}>{t[k]}</button>)}{profile?.role==='admin'&&<button className={tab==='admin'?'active':''} onClick={()=>{setTab('admin');loadAdminPlayers();}}><ShieldCheck size={15}/>{t.adminTab}</button>}</nav>

  {tab==='matches'&&<>{next?<><section className="intro"><div><h2>{t.heading}</h2><p>{t.sub}</p></div><div className="seasonBadge"><ShieldCheck size={17}/>5D</div></section><section className="heroCard"><div className="heroTop"><span>{t.next}</span><b>{next.home===TEAM?t.home:t.away}</b></div><div className="teams"><div><small>{TEAM}</small><h3>{opponent}</h3></div><div className="vs">VS</div></div><div className="meta"><span><CalendarDays size={20}/>{fmtDate(next.date,lang)} · {next.time}</span><button className="venueBtn" onClick={()=>openVenue(next.venue)}><MapPin size={20}/>{next.venue}</button></div><hr/><div className="attendanceHead"><strong>{t.count}</strong><span>{attendanceRows.length} / {players.length}</span></div>{session&&profile?<><div className="attendance"><button disabled={saving} className={attendance==='yes'?'picked':''} onClick={()=>setA('yes')}>✓ {t.yes}</button><button disabled={saving} className={attendance==='no'?'picked':''} onClick={()=>setA('no')}>× {t.no}</button><button disabled={saving} className={attendance==='maybe'?'picked':''} onClick={()=>setA('maybe')}>? {t.maybe}</button></div>{attendance&&<div className="savedRow"><p className="saved">{t.saved}</p><button className="textBtn dangerText" onClick={clearA} disabled={saving}>{t.cancel}</button></div>}</>:<button className="loginCta" onClick={()=>setAuthOpen(true)}><LogIn size={18}/>{t.loginNeeded}</button>}{session&&<div className="responseBoard"><h4>{t.responses}</h4>{attendanceRows.length===0?<p className="muted">{t.noResponses}</p>:<div className="responseCols">{(['yes','maybe','no'] as const).map(k=><div key={k}><b>{k==='yes'?'✓':k==='maybe'?'?':'×'} {t[k]} ({responseGroups[k].length})</b>{responseGroups[k].map(r=><span key={r.player_id}>{avatar(r.players?.display_name||'?',r.players?.avatar_url,'xs')}{r.players?.display_name}</span>)}</div>)}</div>}</div>}{renderDiscussion(next)}</section></>:<section className="panel"><p>Žádný další zápas není v PSMF naplánovaný.</p></section>}
   <h3 className="sectionTitle">{t.upcoming}</h3><div className="list">{matches.filter(m=>m.status==='upcoming').slice(1).map(m=><article className="matchCard" key={m.psmfKey||m.date+m.time}><div className="matchRow"><div className="dateBox"><b>{fmtDate(m.date,lang)}</b><span>{m.time}</span></div><div className="matchTeams"><b>{m.home}</b><span>vs</span><b>{m.away}</b></div><button className="venueBtn" onClick={()=>openVenue(m.venue)}><MapPin size={17}/>{m.venue}</button></div>{renderDiscussion(m)}</article>)}</div>
   <h3 className="sectionTitle">{t.past}</h3><div className="list">{matches.filter(m=>m.status==='past').slice().reverse().map(m=><article className={`matchRow resultRow ${outcome(m.home,m.away,m.homeScore,m.awayScore)}`} key={m.psmfKey||m.date}><div className="dateBox"><b>{fmtDate(m.date,lang)}</b><span>{m.time}</span></div><div className="matchTeams"><b>{m.home}</b><span className="result">{m.result}</span><b>{m.away}</b></div><button className="venueBtn venueText" onClick={()=>openVenue(m.venue)}>{m.venue}</button></article>)}</div></>}

  {tab==='table'&&<section className="panel"><h2>{t.table}</h2><div className="tableWrap"><table><thead><tr><th>{t.pos}</th><th>{t.team}</th><th>{t.played}</th><th>{t.wins}</th><th>{t.draws}</th><th>{t.losses}</th><th>{t.score}</th><th>{t.pts}</th></tr></thead><tbody>{standings.map((r,i)=><tr key={r[0]} className={r[0]===TEAM?'ours':''}><td>{i+1}.</td><td>{r[0]}</td><td>{r[1]}</td><td>{r[2]}</td><td>{r[3]}</td><td>{r[4]}</td><td>{r[5]}</td><td><b>{r[6]}</b></td></tr>)}</tbody></table></div></section>}
  {tab==='stats'&&<><section className="panel"><h2>{t.stats} · 2026 podzim</h2><div className="rosterGrid">{players.map(p=><div className="playerCard" key={p.name}>{avatar(p.name,p.avatarUrl,'lg')}<div><strong>{p.name}</strong><span>{p.games} {t.games.toLowerCase()} · {p.goals} {t.goals.toLowerCase()}</span></div></div>)}</div></section><section className="panel"><h2>{t.career}</h2><div className="tableWrap"><table><thead><tr><th>{t.player}</th><th>{t.games}</th><th>{t.goals}</th></tr></thead><tbody>{career.map(r=><tr key={r.name}><td>{r.name}</td><td>{r.games}</td><td><b>{r.goals}</b></td></tr>)}</tbody></table></div></section></>}
  {tab==='history'&&<section className="panel"><div className="panelHead"><div><h2>{t.history}</h2><p className="muted">PSMF · 2020–2026</p></div><select className="seasonSelect" value={historySeason} onChange={e=>setHistorySeason(e.target.value)}>{seasons.map(s=><option key={s.season} value={s.season}>{s.label} · {s.division}</option>)}</select></div>{selectedSeason&&<div className="seasonSummary"><div><span>{t.rank}</span><strong>{selectedSeason.final_rank?`${selectedSeason.final_rank}.`: '—'}</strong></div><div><span>{t.record}</span><strong>{selectedSeason.wins??0}–{selectedSeason.draws??0}–{selectedSeason.losses??0}</strong></div><div><span>{t.score}</span><strong>{selectedSeason.score||'—'}</strong></div><div><span>{t.pts}</span><strong>{selectedSeason.points??'—'}</strong></div></div>}<div className="list historyList">{selectedSeasonMatches.map(m=><article className={`matchRow resultRow ${outcome(m.home_team,m.away_team,m.home_score,m.away_score)}`} key={m.psmf_key}><div className="dateBox"><b>{fmtDate(new Date(m.kickoff).toLocaleDateString('en-CA',{timeZone:'Europe/Prague'}),lang)}</b><span>{new Date(m.kickoff).toLocaleTimeString('cs-CZ',{timeZone:'Europe/Prague',hour:'2-digit',minute:'2-digit'})}</span></div><div className="matchTeams"><b>{m.home_team}</b><span className="result">{m.home_score}:{m.away_score}</span><b>{m.away_team}</b></div><button className="venueBtn venueText" onClick={()=>m.venue_code&&openVenue(m.venue_code)}>{m.venue_code}</button></article>)}</div>{selectedHistoricalStanding.length>0&&<><h3 className="sectionTitle compactTitle">{t.table}</h3><div className="tableWrap"><table><thead><tr><th>{t.pos}</th><th>{t.team}</th><th>{t.played}</th><th>{t.wins}</th><th>{t.draws}</th><th>{t.losses}</th><th>{t.score}</th><th>{t.pts}</th></tr></thead><tbody>{selectedHistoricalStanding.map(r=><tr key={r.team} className={ours(r.team)?'ours':''}><td>{r.rank}.</td><td>{r.team}</td><td>{r.played}</td><td>{r.wins}</td><td>{r.draws}</td><td>{r.losses}</td><td>{r.score}</td><td><b>{r.points}</b></td></tr>)}</tbody></table></div></>}</section>}
  {tab==='h2h'&&<section className="panel"><div className="panelHead"><div><h2>{t.h2h}</h2><p className="muted">Historie od roku 2020</p></div><select className="seasonSelect" value={h2hOpponent} onChange={e=>setH2hOpponent(e.target.value)}>{opponents.map(o=><option key={o}>{o}</option>)}</select></div><div className="h2hSummary"><strong>{h2hOpponent}</strong><span>{t.meetings}: {h2h.length}</span><span>{t.h2hRecord}: <b>{h2hTotals.w}–{h2hTotals.d}–{h2hTotals.l}</b></span></div>{h2h.length===0?<p className="muted">{t.noH2H}</p>:<div className="list">{h2h.map(m=><article className={`matchRow resultRow ${outcome(m.home_team,m.away_team,m.home_score,m.away_score)}`} key={m.psmf_key}><div className="dateBox"><b>{seasons.find(s=>s.season===m.season)?.label||m.season}</b><span>{m.round}. kolo</span></div><div className="matchTeams"><b>{m.home_team}</b><span className="result">{m.home_score}:{m.away_score}</span><b>{m.away_team}</b></div><span className="venueText">{m.venue_code}</span></article>)}</div>}</section>}

  {tab==='admin'&&profile?.role==='admin'&&<section className="panel"><div className="panelHead"><div><h2>{t.manageTeam}</h2><p className="muted">{lang==='cs'?'Role hráčů, účty, aktivní členové a týmové push notifikace.':'Player roles, accounts, active members and team push notifications.'}</p></div><button className="ghost" onClick={loadAdminPlayers}><RefreshCw size={16}/>{lang==='cs'?'Obnovit':'Refresh'}</button></div><div className="pushAdminBox"><div className="pushAdminHead"><Bell size={19}/><div><strong>{t.adminPush}</strong><span>{lang==='cs'?'Pokud nikoho nevybereš, zpráva půjde všem hráčům s účtem a povoleným push.':'If nobody is selected, the message goes to all players with accounts and push enabled.'}</span></div></div><label>{t.pushTitle}<input value={adminPushTitle} onChange={e=>setAdminPushTitle(e.target.value)}/></label><label>{t.pushMessage}<textarea value={adminPushMessage} onChange={e=>setAdminPushMessage(e.target.value)} placeholder={lang==='cs'?'Např. změna času nebo hřiště…':'For example a time or venue change…'}/></label><div className="pushRecipients"><span>{t.pushRecipients}</span><button type="button" className="textBtn" onClick={()=>setAdminPushPlayers([])}>{t.pushAll}</button><div>{adminPlayers.filter(p=>p.user_id&&p.active).map(p=><label key={p.id}><input type="checkbox" checked={adminPushPlayers.includes(p.id)} onChange={e=>setAdminPushPlayers(v=>e.target.checked?[...v,p.id]:v.filter(id=>id!==p.id))}/>{p.display_name}</label>)}</div></div><button className="primaryBtn pushSendBtn" disabled={adminPushBusy||!adminPushMessage.trim()} onClick={sendAdminPush}><Send size={16}/>{adminPushBusy?'…':t.pushSend}</button></div><div className="adminList">{adminPlayers.map(p=><div className="adminRow" key={p.id}><div className="adminPerson">{avatar(p.display_name,p.avatar_url,'sm')}<div><strong>{p.display_name}</strong><span>{p.email||t.noAccount}</span></div></div><label><span>{t.role}</span><select value={p.role} disabled={adminBusy===p.id} onChange={e=>setPlayerRole(p.id,e.target.value as 'player'|'captain'|'admin')}><option value="player">{t.regularPlayer}</option><option value="captain">{t.captain}</option><option value="admin">{t.admin}</option></select></label><label className="activeToggle"><input type="checkbox" checked={p.active} disabled={adminBusy===p.id} onChange={e=>setPlayerActive(p.id,e.target.checked)}/><span>{t.active}</span></label><button className="unlinkBtn" disabled={!p.user_id||adminBusy===p.id} onClick={()=>unlinkPlayer(p.id)}>{t.unlink}</button></div>)}</div></section>}

  <section className="accountCard"><div className="accountAvatar">{profile?avatar(profile.display_name,profile.avatar_url,'lg'):<Users/>}</div><div className="accountMain"><strong>{t.account}</strong><p>{profile?`${t.signedAs}: ${profile.display_name}`:t.loginNeeded}</p>{session&&profile&&<div className="accountTools"><input ref={avatarInput} hidden type="file" accept="image/jpeg,image/png,image/webp" onChange={uploadAvatar}/><button className="testReminderBtn" onClick={()=>avatarInput.current?.click()} disabled={avatarBusy}><Camera size={16}/>{avatarBusy?'…':t.uploadPhoto}</button><button className="testReminderBtn" onClick={sendTestReminder} disabled={reminderBusy}><Mail size={16}/>{reminderBusy?'…':t.testReminder}</button><button className={`testReminderBtn ${pushPermission==='granted'?'pushOn':''}`} onClick={enablePush} disabled={pushBusy}><Bell size={16}/>{pushBusy?'…':pushPermission==='granted'?t.pushEnabled:t.pushEnable}</button>{pushPermission==='granted'&&<button className="testReminderBtn" onClick={sendTestPush} disabled={pushBusy}><Smartphone size={16}/>{t.pushTest}</button>}{profile.role==='admin'&&<button className="testReminderBtn" onClick={openAdmin}><ShieldCheck size={16}/>{t.manageTeam}</button>}</div>}{session&&profile&&isIos&&!isStandalone&&<p className="pushHint">{t.iosInstall}</p>}</div>{session?<button className="miniBtn" onClick={logout}>{t.logout}</button>:<button className="miniBtn" onClick={()=>setAuthOpen(true)}>{t.login}</button>}</section>
  <footer>Neoficiální týmová aplikace · Data PSMF</footer>

  {venueOpen&&<div className="modalBackdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setVenueOpen(null)}}><div className="authModal venueModal"><button className="modalClose" onClick={()=>setVenueOpen(null)}><X/></button><div className="venueCode"><MapPin size={18}/>{venueOpen.code}</div><h2>{venueOpen.name}</h2><div className="venueAddress"><span>{t.address}</span><strong>{venueOpen.address}</strong></div>{venueOpen.notes&&<p className="venueNotes">{venueOpen.notes}</p>}<div className="navButtons"><a className="primaryBtn navLink" href={googleMaps(venueOpen.address)} target="_blank" rel="noreferrer"><Navigation size={18}/>{t.google}</a><a className="ghost navLink" href={waze(venueOpen.address)} target="_blank" rel="noreferrer"><Navigation size={18}/>{t.waze}</a></div></div></div>}

  {adminOpen&&profile?.role==='admin'&&<div className="modalBackdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setAdminOpen(false)}}><div className="authModal adminModal"><button className="modalClose" onClick={()=>setAdminOpen(false)}><X/></button><h2>{t.manageTeam}</h2><p className="muted adminIntro">{lang==='cs'?'Admin může měnit role, aktivovat/deaktivovat hráče a odpojit účet.':'Admins can change roles, activate/deactivate players and unlink accounts.'}</p><div className="adminList">{adminPlayers.map(p=><div className="adminRow" key={p.id}><div className="adminPerson">{avatar(p.display_name,p.avatar_url,'sm')}<div><strong>{p.display_name}</strong><span>{p.email||t.noAccount}</span></div></div><label><span>{t.role}</span><select value={p.role} disabled={adminBusy===p.id} onChange={e=>setPlayerRole(p.id,e.target.value as 'player'|'captain'|'admin')}><option value="player">{t.regularPlayer}</option><option value="captain">{t.captain}</option><option value="admin">{t.admin}</option></select></label><label className="activeToggle"><input type="checkbox" checked={p.active} disabled={adminBusy===p.id} onChange={e=>setPlayerActive(p.id,e.target.checked)}/><span>{t.active}</span></label><button className="unlinkBtn" disabled={!p.user_id||adminBusy===p.id} onClick={()=>unlinkPlayer(p.id)}>{t.unlink}</button></div>)}</div></div></div>}
  {authOpen&&<div className="modalBackdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setAuthOpen(false)}}><div className="authModal"><button className="modalClose" onClick={()=>setAuthOpen(false)}><X/></button><h2>{authMode==='login'?t.login:t.signup}</h2><div className="authSwitch"><button className={authMode==='login'?'active':''} onClick={()=>{setAuthMode('login');setAuthMessage('')}}>{t.haveAccount}</button><button className={authMode==='signup'?'active':''} onClick={()=>{setAuthMode('signup');setAuthMessage('')}}>{t.newAccount}</button></div><form onSubmit={submitAuth} className="authForm">{authMode==='signup'&&<label>{t.choosePlayer}<select value={selectedPlayer} onChange={e=>setSelectedPlayer(e.target.value)}>{players.map(p=><option key={p.name}>{p.name}</option>)}</select></label>}<label>{t.email}<input type="email" required value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email"/></label><label>{t.password}<input type="password" required minLength={6} value={password} onChange={e=>setPassword(e.target.value)} autoComplete={authMode==='login'?'current-password':'new-password'}/></label><button className="primaryBtn" disabled={authBusy}>{authBusy?'…':authMode==='login'?t.login:t.signup}</button>{authMode==='login'&&<button type="button" className="textBtn" disabled={authBusy} onClick={resendConfirmation}>{t.resend}</button>}{authMessage&&<p className="authMessage">{authMessage}</p>}</form></div></div>}
 </main>;
}
