import { parse } from 'node-html-parser';
export type TeamMatchEvent={
  date:string;
  goals:{player:string;minute:number}[];
  yellowCards:{player:string;minute:number|null}[];
  redCards:{player:string;minute:number|null}[];
  manOfMatch:string[];
  captains:string[];
  goalkeepers:string[];
  appearances:string[];
};

function esc(s:string){return s.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');}
function clean(s:string){return String(s||'').replace(/\s+/g,' ').trim();}
function fold(s:string){return clean(s).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();}
function variants(psmfName:string){
  const n=clean(psmfName), p=n.split(/\s+/);
  const reversed=p.length>=2?[...p.slice(1),p[0]].join(' '):n;
  return [...new Set([n,reversed])].sort((a,b)=>b.length-a.length);
}
function parseDate(line:string){
  const m=line.match(/^(\d{1,2})\.\s*(\d{1,2})\.\s*(\d{2})\b/);
  return m?`20${m[3]}-${m[2].padStart(2,'0')}-${m[1].padStart(2,'0')}`:null;
}
function goalMinutes(text:string,names:string[]){
  const out:number[]=[];
  for(const name of names){
    const re=new RegExp(`((?:\\d{1,2}\\.\\s*,?\\s*)+)${esc(name)}`,'ig');
    for(const m of text.matchAll(re)){
      const start=m.index??0;

      // Card rows on PSMF also look like "44. Player". After raw HTML
      // conversion they are explicitly tagged as [ŽK] / [ČK].
      // Never allow such a card occurrence to pass as a goal.
      const leftBoundary=Math.max(
        text.lastIndexOf('\n',start-1),
        text.lastIndexOf('|',start-1),
        start-80
      );
      const localBefore=text.slice(Math.max(0,leftBoundary+1),start);
      if(/\[(?:ŽK|ČK)\]\s*$/i.test(localBefore))continue;

      out.push(...[...m[1].matchAll(/(\d{1,2})\./g)].map(x=>Number(x[1])));
    }
  }
  return [...new Set(out)].sort((a,b)=>a-b);
}
function markerMinutes(text:string,names:string[],marker:string){
  const out:(number|null)[]=[];
  for(const name of names){
    const e=esc(name), mk=esc(marker);
    for(const re of [
      new RegExp(`(?:(\\d{1,2})\\.\\s*)?${mk}\\s*${e}`,'ig'),
      new RegExp(`(?:(\\d{1,2})\\.\\s*)?${e}\\s*${mk}`,'ig'),
      new RegExp(`${mk}\\s*(?:(\\d{1,2})\\.\\s*)?${e}`,'ig')
    ]){
      for(const m of text.matchAll(re))out.push(m[1]?Number(m[1]):null);
    }
  }

  // Compatibility patterns above can hit the same visual card more than once.
  const seen=new Set<string>();
  return out.filter(minute=>{
    const key=minute==null?'null':String(minute);
    if(seen.has(key))return false;
    seen.add(key);
    return true;
  });
}
function markerBeforeName(line:string,name:string,kind:'star'|'captain'){
  const idx=fold(line).indexOf(fold(name));
  if(idx<0)return false;

  // Check only the short fragment directly before this specific player.
  const before=line.slice(Math.max(0,idx-120),idx);
  const boundary=Math.max(
    before.lastIndexOf(','),
    before.lastIndexOf(';'),
    before.lastIndexOf('|'),
    before.lastIndexOf('–')
  );
  const local=before.slice(boundary+1);

  if(kind==='star')return /\[★ HRÁČ ZÁPASU\]|★|⭐/i.test(local);
  return /\[C KAPITÁN\]|(?:^|\s)C(?:\s|$)/i.test(local);
}

function lineupLine(lines:string[],players:string[]){
  let best=''; let bestCount=0;
  for(const line of lines){
    let count=0;
    for(const player of players){
      if(variants(player).some(v=>fold(line).includes(fold(v))))count++;
    }
    if(count>bestCount){best=line;bestCount=count;}
  }
  return bestCount>=2?best:'';
}

function orderedTeamPlayers(line:string,players:string[]){
  const hits:{player:string;idx:number}[]=[];
  const normalized=fold(line);
  for(const player of players){
    let best=-1;
    for(const v of variants(player)){
      const idx=normalized.indexOf(fold(v));
      if(idx>=0&&(best<0||idx<best))best=idx;
    }
    if(best>=0)hits.push({player,idx:best});
  }
  return hits.sort((a,b)=>a.idx-b.idx).map(x=>x.player);
}


export function detailsTextFromRawHtml(rawHtml:string){
  let html=String(rawHtml||'');
  if(!html)return '';

  // IMPORTANT: these are the exact classes shown by PSMF.
  // The ★ and C are generated by CSS ::before, so they do not exist as normal text.
  // A single player can carry BOTH classes; both markers are intentionally preserved.
  html=html.replace(
    /<span\b([^>]*\bclass\s*=\s*["'][^"']*\bis-best\b[^"']*["'][^>]*)>/gi,
    ' [★ HRÁČ ZÁPASU] <span$1>'
  );
  html=html.replace(
    /<span\b([^>]*\bclass\s*=\s*["'][^"']*\bis-captain\b[^"']*["'][^>]*)>/gi,
    ' [C KAPITÁN] <span$1>'
  );

  // PSMF renders yellow/red cards as CSS-decorated spans too.
  // Their visible card icon is generated by CSS, so preserve the semantic marker
  // in text before stripping HTML. The span text itself can be e.g. "46. Martin Černý".
  html=html.replace(
    /<span\b([^>]*\bclass\s*=\s*["'][^"']*\bis-yellow\b[^"']*["'][^>]*)>/gi,
    ' [ŽK] <span$1>'
  );
  html=html.replace(
    /<span\b([^>]*\bclass\s*=\s*["'][^"']*\bis-red\b[^"']*["'][^>]*)>/gi,
    ' [ČK] <span$1>'
  );

  // Preserve the same visual row/cell boundaries the existing text parser expects.
  html=html
    .replace(/<br\s*\/?>/gi,'\n')
    .replace(/<\/(tr|p|div|li|h1|h2|h3|h4|h5|section|article|table|tbody|thead)>/gi,'\n')
    .replace(/<\/td>/gi,' | ');

  const text=parse(`<div>${html}</div>`).text
    .replace(/\u00a0/g,' ')
    .replace(/[ \t]+/g,' ')
    .replace(/ *\| */g,' | ')
    .replace(/\n[ \t]+/g,'\n');

  return text.split(/\n+/).map(x=>x.trim()).filter(Boolean).join('\n');
}

export function parseSeasonDetails(detailsText:string,players:string[]):TeamMatchEvent[]{
  const lines=String(detailsText||'').split(/\n+/).map(s=>s.trim()).filter(Boolean);
  const chunks:{date:string,lines:string[]}[]=[];
  let current:{date:string;lines:string[]}|null=null;
  for(const line of lines){
    const date=parseDate(line);
    if(date){
      if(current)chunks.push(current);
      current={date,lines:[line]};
    }else if(current)current.lines.push(line);
  }
  if(current)chunks.push(current);

  return chunks.map(({date,lines})=>{
    const text=lines.join('\n');
    const goals:{player:string;minute:number}[]=[];
    const yellowCards:{player:string;minute:number|null}[]=[];
    const redCards:{player:string;minute:number|null}[]=[];
    const manOfMatch:string[]=[];
    const captains:string[]=[];
    const goalkeepers:string[]=[];

    const lineup=lineupLine(lines,players);
    const ordered=lineup?orderedTeamPlayers(lineup,players):[];

    // PSMF convention confirmed by team page: first listed player is the goalkeeper.
    if(ordered[0])goalkeepers.push(ordered[0]);

    for(const player of players){
      const names=variants(player);
      for(const minute of goalMinutes(text,names))goals.push({player,minute});
      for(const minute of markerMinutes(text,names,'[ŽK]'))yellowCards.push({player,minute});
      for(const minute of markerMinutes(text,names,'[ČK]'))redCards.push({player,minute});
      if(lineup && names.some(name=>markerBeforeName(lineup,name,'star')))manOfMatch.push(player);
      if(lineup && names.some(name=>markerBeforeName(lineup,name,'captain')))captains.push(player);
    }
    return {
      date,
      goals:goals.sort((a,b)=>a.minute-b.minute),
      yellowCards,
      redCards,
      manOfMatch:[...new Set(manOfMatch)],
      captains:[...new Set(captains)],
      goalkeepers:[...new Set(goalkeepers)],
      appearances:[...new Set(ordered)]
    };
  });
}
