-- Kabina v2.3: hřiště + emailové reminders. Run once in Supabase SQL Editor -> Database.
-- Safe to re-run.

create table if not exists public.venues (
  code text primary key,
  name text not null,
  address text not null,
  notes text,
  source_url text,
  synced_at timestamptz not null default now()
);
alter table public.venues enable row level security;
drop policy if exists "venues readable" on public.venues;
create policy "venues readable" on public.venues for select using (true);

create table if not exists public.reminder_log (
  id bigint generated by default as identity primary key,
  match_id uuid not null references public.matches(id) on delete cascade,
  player_id uuid not null references public.players(id) on delete cascade,
  kind text not null default 'attendance-2d',
  sent_to text,
  sent_at timestamptz not null default now()
);
create unique index if not exists reminder_once_uidx on public.reminder_log(match_id,player_id,kind);
alter table public.reminder_log enable row level security;
-- No public policies: reminder history is server-only.
