-- Kabina v2.2: run once in Supabase SQL Editor -> Database. Safe to re-run.

alter table public.players add column if not exists psmf_games int not null default 0;
alter table public.players add column if not exists psmf_goals int not null default 0;
alter table public.players add column if not exists last_seen_at timestamptz;

-- Public sports roster/statistics are readable before registration so the signup list stays current.
drop policy if exists "players readable public" on public.players;
create policy "players readable public" on public.players for select to anon, authenticated using (true);

create table if not exists public.standings (
  id bigint generated by default as identity primary key,
  season text not null,
  rank int not null,
  team text not null,
  played int not null default 0,
  wins int not null default 0,
  draws int not null default 0,
  losses int not null default 0,
  score text not null default '0:0',
  points int not null default 0,
  synced_at timestamptz not null default now()
);
create unique index if not exists standings_season_team_uidx on public.standings(season,team);
alter table public.standings enable row level security;
drop policy if exists "standings readable" on public.standings;
create policy "standings readable" on public.standings for select using (true);

create table if not exists public.sync_meta (
  key text primary key,
  last_synced_at timestamptz not null default now(),
  source_url text
);
alter table public.sync_meta enable row level security;
drop policy if exists "sync meta readable" on public.sync_meta;
create policy "sync meta readable" on public.sync_meta for select using (true);

-- Full 2026 squad: do not delete older players merely because they have not appeared this autumn.
insert into public.players (display_name, psmf_name, psmf_games, psmf_goals, active)
values
  ('Bouzek Filip Oliver','Bouzek Filip Oliver',0,0,true),
  ('Černý Martin','Černý Martin',3,0,true),
  ('Dusil Jan','Dusil Jan',0,0,true),
  ('Herko Daniel','Herko Daniel',0,0,true),
  ('Horák Adam','Horák Adam',3,0,true),
  ('Jelenčiak Jakub','Jelenčiak Jakub',2,2,true),
  ('Kolář Adam','Kolář Adam',3,0,true),
  ('Kozák Tomáš','Kozák Tomáš',0,0,true),
  ('Kubala Martin','Kubala Martin',3,0,true),
  ('Landfeld Jan','Landfeld Jan',2,1,true),
  ('Landfeld Vít','Landfeld Vít',3,0,true),
  ('Sigmund Radek','Sigmund Radek',3,0,true),
  ('Varner Howard','Varner Howard',3,0,true),
  ('Veselý Mikuláš','Veselý Mikuláš',3,0,true)
on conflict (display_name) do update set active=true;

insert into public.standings (season,rank,team,played,wins,draws,losses,score,points)
values
 ('2026-podzim',1,'Batalion 91 A',4,3,0,1,'21:9',6),
 ('2026-podzim',2,'Penál AFK',3,3,0,0,'12:1',6),
 ('2026-podzim',3,'Santovi Sobi',4,3,0,1,'18:9',6),
 ('2026-podzim',4,'Favorit FC',4,3,0,1,'14:9',6),
 ('2026-podzim',5,'Olexton FC',4,2,1,1,'15:7',5),
 ('2026-podzim',6,'Botič FC',3,2,0,1,'15:11',4),
 ('2026-podzim',7,'Credit Praha FC',4,2,0,2,'14:18',4),
 ('2026-podzim',8,'Masáže FC',4,1,1,2,'9:18',3),
 ('2026-podzim',9,'XXX',4,1,0,3,'9:10',2),
 ('2026-podzim',10,'Cirkus Praha',4,0,1,3,'7:16',1),
 ('2026-podzim',11,'Pěstební dělníci A',3,0,1,2,'3:12',1),
 ('2026-podzim',12,'Princ Praha FC',3,0,0,3,'5:22',0)
on conflict (season,team) do update set rank=excluded.rank,played=excluded.played,wins=excluded.wins,draws=excluded.draws,losses=excluded.losses,score=excluded.score,points=excluded.points,synced_at=now();
